name: Javadocs

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Generate Javadocs
        run: ./gradlew javadoc
